version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/polisportiva
    depends_on:
      - db

  db:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: polisportiva
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin