version: '3'

services:
  db:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: polisportiva
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/polisportiva
    depends_on:
      - db
